import puppeteer from "puppeteer-core";
import path from "node:path";
const ext = path.resolve(process.argv[2]);
const browser = await puppeteer.launch({ executablePath: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", headless: true, pipe: true, enableExtensions: true, protocolTimeout: 40000 });
const id = await browser.installExtension(ext);
const target = await browser.waitForTarget((t) => t.type() === "service_worker" && t.url().includes(id));
const worker = await target.worker();
worker.on("console", (m) => console.log("SW:", m.text()));
const step = (name, fn) => worker.evaluate(fn).then((v) => console.log(name, JSON.stringify(v))).catch((e) => console.log(name, "ERR", e.message));
await step("globals", () => ({ start: typeof startAttendanceBackground, solve: typeof solveCaptchaViaOffscreen }));
await step("alarm", async () => Boolean(await chrome.alarms.get("cuims-clear-attendance")));
await step("offscreen", async () => { await ensureOffscreen(); return chrome.offscreen.hasDocument(); });
await step("prewarm", async () => chrome.runtime.sendMessage({ type: "cuims-clear:prewarm" }));
await step("bytes", async () => chrome.runtime.sendMessage({ type: "cuims-clear:solve-captcha-bytes", dataUrl: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==" }));
for (const t of browser.targets()) console.log("target", t.type(), t.url());
await browser.close();
