#!/usr/bin/env python3
"""Builds captcha-glyphs.js: the 62 glyphs of the CUIMS captcha font.

CUIMS draws its captcha with Courier New Bold at 20 px, four characters on a
fixed 12.25 px pitch starting at x = 3 (fitted against the labelled corpus in
work/corpus, NCC 0.96). Each glyph is rendered once at 4x and stored as a
1-bit mask with its offset from the pen position, in 4x pixels. The solver
box-filters these masks down to any quarter-pixel position at run time.

Needs Pillow and Courier New Bold (bundled with macOS and Windows):
    python3 scripts/build-captcha-glyphs.py
"""
import base64
import os
import sys

from PIL import Image, ImageDraw, ImageFont

FONT_PATHS = [
    "/System/Library/Fonts/Supplemental/Courier New Bold.ttf",
    "C:/Windows/Fonts/courbd.ttf",
]
ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"
SIZE = 20
SCALE = 4
MARGIN = 40
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "outputs", "cuims-clear-firefox", "captcha-glyphs.js")


def main():
    font_path = next((p for p in FONT_PATHS if os.path.exists(p)), None)
    if not font_path:
        sys.exit("Courier New Bold not found")
    font = ImageFont.truetype(font_path, SIZE * SCALE)
    rows = []
    for ch in ALPHABET:
        canvas = Image.new("L", (200, 200), 0)
        ImageDraw.Draw(canvas).text((MARGIN, MARGIN), ch, font=font, fill=255)
        mask = canvas.point(lambda v: 255 if v >= 128 else 0)
        left, top, right, bottom = mask.getbbox()
        w, h = right - left, bottom - top
        bits = bytearray((w * h + 7) // 8)
        pixels = mask.load()
        for y in range(h):
            for x in range(w):
                if pixels[left + x, top + y]:
                    i = y * w + x
                    bits[i >> 3] |= 1 << (i & 7)
        data = base64.b64encode(bytes(bits)).decode()
        rows.append(f'    "{ch}": [{left - MARGIN}, {top - MARGIN}, {w}, {h}, "{data}"],')
    body = "\n".join(rows)
    with open(OUT, "w") as out:
        out.write(
            "// Generated by scripts/build-captcha-glyphs.py. Do not edit.\n"
            "// The CUIMS captcha font (Courier New Bold, 20 px) at 4x: per glyph\n"
            "// [x offset, y offset, width, height, 1-bit mask, rows from the top].\n"
            "(function (root) {\n"
            "  root.CuimsCaptchaGlyphs = {\n"
            f"    size: {SIZE},\n    scale: {SCALE},\n    glyphs: {{\n{body}\n    }},\n  }};\n"
            "})(globalThis);\n"
        )
    print(f"wrote {OUT} ({os.path.getsize(OUT)} bytes)")


if __name__ == "__main__":
    main()
